<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>EcoTech.Catalog.Api</RootNamespace>
    <UserSecretsId>ecotech-catalog-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcoTech.Catalog.Application\EcoTech.Catalog.Application.csproj" />
    <ProjectReference Include="..\EcoTech.Catalog.Infrastructure\EcoTech.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EcoTech.BuildingBlocks.Observability\EcoTech.BuildingBlocks.Observability.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EcoTech.BuildingBlocks.Web\EcoTech.BuildingBlocks.Web.csproj" />
  </ItemGroup>

</Project>
