<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Techodist.Order.Api</RootNamespace>
    <UserSecretsId>techodist-order-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Techodist.Order.Application\Techodist.Order.Application.csproj" />
    <ProjectReference Include="..\Techodist.Order.Infrastructure\Techodist.Order.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Techodist.BuildingBlocks.Observability\Techodist.BuildingBlocks.Observability.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Techodist.BuildingBlocks.Web\Techodist.BuildingBlocks.Web.csproj" />
  </ItemGroup>

</Project>
