<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Techodist.Basket.Api</RootNamespace>
    <UserSecretsId>techodist-basket-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Techodist.Basket.Application\Techodist.Basket.Application.csproj" />
    <ProjectReference Include="..\Techodist.Basket.Infrastructure\Techodist.Basket.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Techodist.BuildingBlocks.Observability\Techodist.BuildingBlocks.Observability.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Techodist.BuildingBlocks.Web\Techodist.BuildingBlocks.Web.csproj" />
  </ItemGroup>

</Project>
