<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EcoTech.Catalog.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcoTech.Catalog.Domain\EcoTech.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EcoTech.BuildingBlocks.Core\EcoTech.BuildingBlocks.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EcoTech.Catalog.UnitTests" />
  </ItemGroup>

</Project>
